version: '2'

services:
    tests:
        extends:
            file: common.yml
            service: web
        entrypoint: python3 cli/run.py -e defaults.env,tests/test.env,docker/tests.env,tests/local.env ./docker/runtests
        links:
            - test_db
    test_db:
        image: postgres:9.6
